# Generated by Django 3.2.16 on 2023-10-28 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LetterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senders_name', models.CharField(max_length=128)),
                ('receiver_name', models.CharField(max_length=128)),
                ('point_of_departure', models.TextField()),
                ('pick_up_piont', models.TextField()),
                ('sender_index', models.IntegerField()),
                ('recipient_index', models.IntegerField()),
                ('letter_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='letters.lettercategory')),
            ],
        ),
    ]
