# Generated by Django 3.2.16 on 2023-10-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LetterCategory',
            new_name='LettersCategory',
        ),
    ]
