# Generated by Django 3.2.16 on 2023-10-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0003_rename_letter_letters'),
    ]

    operations = [
        migrations.AddField(
            model_name='letters',
            name='mail_weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
