# Generated by Django 3.2.16 on 2023-10-28 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0004_letters_mail_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='letters',
            name='letter_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='letters.letterscategory'),
        ),
    ]
