# Generated by Django 3.2.16 on 2023-11-02 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parcels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senders_name', models.CharField(max_length=128)),
                ('receiver_name', models.CharField(max_length=128)),
                ('point_of_departure', models.TextField()),
                ('pick_up_piont', models.TextField()),
                ('sender_index', models.IntegerField()),
                ('recipient_index', models.IntegerField()),
                ('phone_number', models.CharField(max_length=10)),
                ('pay_sum', models.IntegerField(blank=True, null=True)),
                ('parcel_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='parcels.parcelscategory')),
            ],
        ),
    ]
